FROM jenkins/jenkins:lts-jdk11

USER root

RUN apt-get update

RUN apt-get -qy full-upgrade && \
    apt-get install -qy curl && \
    curl -sSL https://get.docker.com/ | sh

WORKDIR /var/jenkins_home

RUN usermod -aG docker jenkins

EXPOSE 8080
EXPOSE 50000

USER jenkins
